#title: Notes about Networks
author: S Paul
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Network Graphs | Visualization

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  s-paul-s # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

google_analytics: G-BQR8273TKB
